---
- name: 关闭交换分区
  command: swapoff --all

- name: 基础软件安装
  yum: name={{item}} state=present
  with_items:
    - gcc
    - gcc-c++
    - wget
    - lrzsz
    - telnet
    - net-tools
    - epel*
    - vim
    - unzip
    - ntpdate
    - yum-utils
    - device-mapper-persistent-data
    - conntrack-tools
    - libseccomp
    - libtool-ltdl

- name: 关闭防火墙
  service: name=firewalld state=stopped enabled=no

- name: 开启ntpdate
  service: name=ntpdate state=started enabled=yes

- name: ntp同步
  cron: name='ntpdate' minute="20" job="/usr/sbin/ntpdate time7.aliyun.com"

- name: ulimit设置
  shell: echo "* soft nofile 65536" >> /etc/security/limits.conf && echo "* hard nofile 65536" >> /etc/security/limits.conf  && echo "* soft nproc 65536"  >> /etc/security/limits.conf && echo "* hard nproc 65536"  >> /etc/security/limits.conf && echo "* soft  memlock  unlimited"  >> /etc/security/limits.conf && echo "* hard memlock  unlimited"  >> /etc/security/limits.conf

- name:  开启 forward
  shell: modprobe br_netfilter && echo net.ipv4.ip_forward = 1 >  /etc/sysctl.d/k8s.conf && echo net.bridge.bridge-nf-call-ip6tables = 1  >> /etc/sysctl.d/k8s.conf && echo net.bridge.bridge-nf-call-iptables = 1  >> /etc/sysctl.d/k8s.conf  && sysctl -p /etc/sysctl.d/k8s.conf

- name: 拷贝sysctl文件
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
- name: 加载sysctl文件
  shell: sysctl --system

- name: hosts 分发
  template:  src=../templates/hosts.j2  dest=/etc/hosts

- name: 设置主机名称
  shell: hostname {{ hostname | quote }} > /etc/hostname

- name: 改变主机名
  shell: hostnamectl set-hostname {{ hostname | quote }}

- name: 挂载阿里云data数据盘
  mount: src=/dev/vdb1 path=/data fstype=xfs opts=defaults state=mounted
  when: machine_type == "aliyun"
